# Generated by Django 6.0.4 on 2026-04-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('resume', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='image',
            field=models.ImageField(blank='true', null=True, upload_to='articulos'),
        ),
    ]
