# Generated by Django 6.0.4 on 2026-04-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_articulo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='fecha',
            new_name='fecha_publicacion',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='resume',
            new_name='resumen',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='image',
        ),
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='articulos/'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='autor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
